### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by mayank99**
~~simpl 2.0 because it's simple~~ "use GPLv3 like a normal person"

### CODE REVIEW

**Comment by TortoiseWrath** [comment]
SimPL 2.0 is not even close to FSF-approved and is not GPLv3 compatible (only GPLv2 compatible, with no "any later version" clause in sight other than the disastrously vague "substantially similar license"). Just use GPLv3 if you want a copyleft license

**Comment by mayank99** [comment]
But GPL 3 is so long, I don't want to read all that.

**Comment by TortoiseWrath** [comment]
Literally everyone who cares already knows the terms of GPL3 and will in fact have to read less than I had to read to figure out wtf this license is

**Comment by mayank99** [comment]
Yeah, I was trying to make github detect it and failed because this license SUCKS

**Comment by mayank99** [comment]
Beautiful
image

**Pull request merged**
