### PR TITLE
Add URL item

### LINKED ISSUE #99: Implement website/URL item
So users can add generic links to their profile

### PR DESCRIPTION
**Pull request by TortoiseWrath**
closes #99

### CODE REVIEW

**Comment by mayank99** [comment]
Is this the same field as "website" under a base contact?

**Comment by TortoiseWrath** [comment]
oh god is it

**Comment by TortoiseWrath** [comment]
i didn't notice base contact had that

**Comment by mayank99** [comment]
It apparently doesn't, which is a good thing because a URL is not necessarily a contact's website. It can just be a generic field, speaking of which, we need to add a generic text field.

**Pull request merged**
