### PR TITLE
Fix hive generator error and twitter tests

### LINKED ISSUE #193: Hive generator fails to generate typeId for MultaccContactAdapter
This is breaking the build for CI/CD and on Micah's machine

```
Compiler message:
../lib/database/contact_model.g.dart:9:7: Error: The non-abstract class 'MultaccContactAdapter' is missing implementations for these members:
 - TypeAdapter.typeId
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class MultaccContactAdapter extends TypeAdapter<MultaccContact> {
      ^^^^^^^^^^^^^^^^^^^^^
../../programs/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.1+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;
          ^^^^^^
```

### PR DESCRIPTION
**Pull request by mayank99**
Closes #193

### CODE REVIEW

**Comment by TortoiseWrath** [comment]
I think this is actually wrong and Micah needed this because he was somehow using an *older* version of Hive (1.2.0) - it was changed in 1.3.0

**Comment by mayank99** [comment]
That actually makes a lot of sense lmfao

**Comment by mayank99** [comment]
It's a draft, you don't need to close this

**Comment by TortoiseWrath** [comment]
cherry-pick a4a7011 and 3ecc3aa into another branch and open a PR with those since 96609ac breaks everything

**Comment by mayank99** [comment]
The hive generator still fails though. Were you working on a manual `TypeAdapter` for contact model?

**Comment by TortoiseWrath** [comment]
don't need one, just need a non-failing generator :exceptionallyfastparrot: which yes I am working on

**Comment by mayank99** [comment]
It's a draft, leave me alone

**Comment by mayank99** [comment]
About to be not-a-draft. We can squash this or I can rewrite history or open a new PR

**Comment by mayank99** [comment]
This PR is bad and invalid and the author should feel bad and invalid.

**Pull request closed without merging**
