### PR TITLE
Require Hive 1.4 in pubspec

### LINKED ISSUE #193: Hive generator fails to generate typeId for MultaccContactAdapter
This is breaking the build for CI/CD and on Micah's machine

```
Compiler message:
../lib/database/contact_model.g.dart:9:7: Error: The non-abstract class 'MultaccContactAdapter' is missing implementations for these members:
 - TypeAdapter.typeId
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class MultaccContactAdapter extends TypeAdapter<MultaccContact> {
      ^^^^^^^^^^^^^^^^^^^^^
../../programs/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.1+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;
          ^^^^^^
```

### PR DESCRIPTION
**Pull request by TortoiseWrath**
This should close #193 by allowing flutter to get the correct Hive version

### CODE REVIEW

**Comment by mayank99** [comment]
um, why not just put the dependency override and leave the versions to be `any`?

**Comment by TortoiseWrath** [comment]
Because having the versions as `any` is what caused this in the first place lmao; hive is unstable enough at this point in its development that 1.3 and 1.4 were both breaking versions, so 1.5 probably will be too

**Comment by TortoiseWrath** [comment]
and specifying minimum hive version means Micah et al won't have to upgrade dependencies to automatically get a non-broken hive

**Comment by mayank99** [comment]
No, the issue was caused by @micah-white not running `flutter upgrade` like ever

**Comment by TortoiseWrath** [comment]
that really shouldn't be an issue if your dependencies are set correctly; `: any` isn't really a good practice because it causes these issues and means your code may randomly stop building in the future when a breaking change is made to a dependency

**Comment by mayank99** [comment]
Source on "not good practice"?

**Comment by TortoiseWrath** [comment]
logic :exceptionallyfastparrot:

**Comment by TortoiseWrath** [comment]
also https://flutter.dev/docs/development/packages-and-plugins/using-packages seems to strongly favor `^version`, as does virtually every other dependency management system for the reasons mentioned above

**Comment by mayank99** [comment]
image
hrm.

**Comment by TortoiseWrath** [comment]
I'm struggling to find many sources explicitly stating `any` is a bad idea since this is so obvious. I did find one article that assumes this fact is painfully obvious to the reader: 
image

**Comment by TortoiseWrath** [comment]
> 
> 
> image
> hrm.

it's almost like the point of that example isn't the version number of `some_package` and `another_package`

**Comment by TortoiseWrath** [comment]
also this is how it is in the hive docs https://docs.hivedb.dev/#/

**Comment by TortoiseWrath** [comment]
https://dart.dev/tools/pub/dependencies#version-constraints

> While any is allowed, we do not recommend it for performance reasons.

That isn't really the reason I was thinking but ok

**Comment by mayank99** [comment]
wut no, that is valid syntax.

The point of using `: any`  or just `: ` is that you don't have to worry about making a commit or PR whenever you run `flutter pub upgrade`

**Comment by TortoiseWrath** [comment]
Wut? The point of **not** using `: any` is that you don't have to worry about making a commit or PR whenever you run `flutter pub upgrade`. Using `any` means **flutter pub upgrade can break your code** when breaking changes are made to the dependencies

**Comment by TortoiseWrath** [comment]
not flutter pubspec, but https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md is good advice in general for dependency management

**Pull request merged**
