### PR TITLE
Tests

### LINKED ISSUE #201: Write at least 5 tests
- Required for sprint-3.
- Can be unit/integration/widget/driver tests

### PR DESCRIPTION
**Pull request by TortoiseWrath**
moved Micah's tests to a new branch

Closes #201

### CODE REVIEW

**Comment by TortoiseWrath** [comment]
let's not squash, he needs more commits, also I bet the tests won't pass anymore after merging #215 into this branch

**Comment by mayank99** [comment]
Those commit messages are bad So it needs to be squashed.

**Comment by TortoiseWrath** [comment]
you are literally going to take away his grade because of the verb tense in his commit messages?

**Comment by TortoiseWrath** [comment]
Don't merge this until after build check

**Pull request merged**
