### PR TITLE
remove "convention" for constants

### PR DESCRIPTION
**Pull request by TortoiseWrath**
since it is unconventional

https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names
https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters

### CODE REVIEW

**Comment by mayank99** [comment]
This PR should really also include converting all constants to a universal format. I've been meaning to make a `Constants` class with static camel case members to replace the k- convention.

**Comment by mayank99** [comment]
Actually, scratch that. I think I've posted this link before:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#naming

**Comment by TortoiseWrath** [comment]
Yeah, and we had a conversation about that and figured out that entire style guide was bullshit :exceptionallyfastparrot:

**Comment by TortoiseWrath** [comment]
closing this because it's not useful and i don't want it in the pull requests tab lmao

**Pull request closed without merging**
